site_name: Cuadratura Gaussiana

theme:
  name: "material"

plugins:
  - mkdocstrings
#Se crea una 'configuración' en el .yml para permitir que las ecuaciones de LaTeX se rendericen de forma correcta
markdown_extensions: #Configuración de extensiones que amplían las capacidades del Markdown
  - pymdownx.arithmatex: #Permite escribir ecuaciones en formato LaTeX en los archivos Markdown
      generic: true #Habilita el soporte de delimitadores como '$$' para generar ecuaciones

extra_javascript: #PErmite cargar archivos adicionales al sitio web ya que no me cargaba con lo anterior
  - https://polyfill.io/v3/polyfill.min.js?features=es6 #Asegura las funcionalidades modernas de js en cualquier navegador (yo utilizo brave y no me cargaban)
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Renderiza las ecuaciones

nav: #Pestaña de navegación
  - index.md #Genera el índice de contenidos
  - explanation.md #Se hace la explicación de la Cuadratura Gaussiana
  - tutorials.md #Se importa el .py para la visualización de este en el servidor 
